### PR TITLE
Use bounded queue to avoid flooding

### LINKED ISSUE #1: Splash screen message wrong approach?
This is an issue I previously fixed (I think, unless that was on a branch), but has been reintroduced during the migration into a library.

The Splash screen maintains a queue of upcoming messages, and works through them one by one at a fixed time per message. However, this makes it vulnerable to flooding - if messages are received faster than the fixed time, the displayed message will lag further and further behind the current activity.

Instead I suggest the splash screen should only queue up a single message - if a new message is posted, that should override the currently queued message. This will result in some messages not being shown, but will mean that the splash screen's message will reflect the current or recent activity.

### PR DESCRIPTION
**Pull request by msteiger**
Default queue length is 3 messages.

Fixes #1

### CODE REVIEW

**Comment by Cervator** [comment]
Any real testing needed here or want to just merge it? Might be something to set this up so it can be pulled to /libs in a Terasology mega-workspace and used directly for easier testing.

File: src/main/java/org/terasology/splash/AbstractSplashScreen.java [hunk 1]
```diff
@@ -96,19 +100,30 @@ public void close() {
 
     @Override
     public void post(String message) {
-        if (message != null) {
+        if (message == null) {
+            return;
+        }
+
+        synchronized (lock) {
             messageQueue.add(message);
```
Comment (immortius) [inline src/main/java/org/terasology/splash/AbstractSplashScreen.java]: This will actually throw an exception if the queue is full. You might want messageQueue.offer(message) - except that will cause the new message to be dropped if the queue is full. The desired behavior is probably to drop the oldest message, not the newest one.

Comment (msteiger) [inline src/main/java/org/terasology/splash/AbstractSplashScreen.java]: The actual queue is unbounded. However, messages are processed without delay as long as the queue is overfull. This ensures that all messages are seen and corresponding events are triggered.
